version: '3.9'
services:
  web:
    build:
      target: base-stage
    restart: 'no'
    volumes:
      - ./:/app
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '10'
    environment:
      VIRTUAL_HOST: voladi.voladi.local
      DJANGO_DEBUG: 'true'
      STATIC_EXPIRES: 1s
      EMAIL_BACKEND: django.core.mail.backends.filebased.EmailBackend

  database:
    restart: 'no'
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '10'

  redis:
    restart: 'no'
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '10'
